spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/starbucks_menu
    username: anshul.bansal@mambu.com
    password: 
    driver-class-name: org.postgresql.Driver
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3.2
      embedding:
        model: nomic-embed-text
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: true

server:
  port: 8080

logging:
  level:
    com.starbucks.menuaichat: INFO
    org.springframework.ai: INFO
    org.springframework.web: INFO
    org.springframework.jdbc: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/starbucks-menu.log